### ISSUE TITLE
Panics on non-struct types

### ISSUE THREAD

**Issue by hasufell** [leanovate/gopter#28]
It seems to me this library has less powerful "generator inference" than the simple `testing/quick` one, which has no problem with this case or with https://github.com/leanovate/gopter/issues/27

---

Given this input program

```go
package main

import (
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/arbitrary"
)

type MyIDType int32

type Foo struct {
	Name string
	Id   MyIDType
}

func main() {
	parameters := gopter.DefaultTestParameters()
	parameters.Rng.Seed(1234)

	arbitraries := arbitrary.DefaultArbitraries()

	properties := gopter.NewProperties(parameters)

	properties.Property("Foo", arbitraries.ForAll(
		func(foo *Foo) bool {
			return true
		}))

	properties.Run(gopter.ConsoleReporter(false))
}
```

Output:

```
! Foo: Error on property evaluation after 0 passed tests: Check paniced:
   reflect.Set: value of type int32 is not assignable to type main.MyIDType
   goroutine 1 [running]:
runtime/debug.Stack(0xc42004b788, 0x4f0980, 0xc42007e4d0)
	/usr/x86_64-pc-linux-gnu/lib/go/src/runtime/debug/stack.go:24 +0xa7
github.com/hasufell/gopter-examples/vendor/github.com/leanovate/gopter.Save
  Prop.func1.1(0xc42004bd28)
	/home/julian/go/src/github.com/hasufell/gopter-examples/vendor/github.com/
  leanovate/gopter/prop.go:19 +0x6e
panic(0x4f0980, 0xc42007e4d0)
	/usr/x86_64-pc-linux-gnu/lib/go/src/runtime/panic.go:505 +0x229
reflect.Value.assignTo(0x4f0340, 0xc42008bdf8, 0x85, 0x521cbc, 0xb,
   0x4f0400, 0x0, 0x4f0340, 0x4f0340, 0xc42008bdf8)
	/usr/x86_64-pc-linux-gnu/lib/go/src/reflect/value.go:2235 +0x427
reflect.Value.Set(0x4f0400, 0xc4200bc4d0, 0x185, 0x4f0340, 0xc42008bdf8,
   0x85)
	/usr/x86_64-pc-linux-gnu/lib/go/src/reflect/value.go:1373 +0xa4
github.com/hasufell/gopter-examples/vendor/github.com/leanovate/gopter/gen.
  StructPtr.func1(0xc4200bc480, 0x1)
	/home/julian/go/src/github.com/hasufell/gopter-examples/vendor/github.com/
  leanovate/gopter/gen/struct.go:64 +0x327
github.com/hasufell/gopter-examples/vendor/github.com/leanovate/gopter/prop
  .ForAll.func1(0xc4200bc480, 0x529668)
	/home/julian/go/src/github.com/hasufell/gopter-examples/vendor/github.com/
  leanovate/gopter/prop/forall.go:31 +0x140
github.com/hasufell/gopter-examples/vendor/github.com/leanovate/gopter.Save
  Prop.func1(0xc4200bc480, 0x0)
	/home/julian/go/src/github.com/hasufell/gopter-examples/vendor/github.com/
  leanovate/gopter/prop.go:24 +0x6c
github.com/hasufell/gopter-examples/vendor/github.com/leanovate/gopter.Prop
  .Check.func1(0x0, 0xc42007e470, 0x5d4f60)
	/home/julian/go/src/github.com/hasufell/gopter-examples/vendor/github.com/
  leanovate/gopter/prop.go:52 +0x15c
github.com/hasufell/gopter-examples/vendor/github.com/leanovate/gopter.(*ru
  nner).runWorkers(0xc420082720, 0x0)
	/home/julian/go/src/github.com/hasufell/gopter-examples/vendor/github.com/
  leanovate/gopter/runner.go:45 +0x2d9
github.com/hasufell/gopter-examples/vendor/github.com/leanovate/gopter.Prop
  .Check(0xc42007e450, 0xc4200a05c0, 0x520b0c)
	/home/julian/go/src/github.com/hasufell/gopter-examples/vendor/github.com/
  leanovate/gopter/prop.go:110 +0x1af
github.com/hasufell/gopter-examples/vendor/github.com/leanovate/gopter.(*Pr
  operties).Run(0xc4200822a0, 0x538c20, 0xc4200bc440, 0x3)
	/home/julian/go/src/github.com/hasufell/gopter-examples/vendor/github.com/
  leanovate/gopter/properties.go:37 +0xc9
main.main()
	/home/julian/go/src/github.com/hasufell/gopter-examples/gopterexamples.go:
  28 +0x19d
```

**Comment by untoldwind** [comment]
Added a slightly extended variant to the examples.

**Comment by hasufell** [comment]
cool 👍
